### ISSUE TITLE
Operate on touch and get ends with error code 2.

### ISSUE THREAD

**Issue by batchenoz** [aerospike/aerospike-client-java#102]
`client.operate(writePolicy, key, Operation.touch(), Operation.get(bin)`

The touch operation succeeds, but the 'get' results with error code 2 (missing key).
When running every operation by itself, each works.
When changing the order of operations, we get the same result (touch succeeds, get fails).

**Comment by BrianNichols** [comment]
operate() only works on existing records.  operate() will fail with error code 2 when the record does not exist.  touch() is not used to create records.  Instead, touch() is used to reset/extend the expiration time (ttl) of an existing record.

**Comment by batchenoz** [comment]
Operate can also create  a record if the policy allows it.

In my example I tried to read and update ttl in one atomic operation.
Of course I tried it on an existing record.
As I wrote, on the existing record the ttl was updated, but the read operation raised an exception with error code 2.

**Comment by BrianNichols** [comment]
Please provide an example program that reproduces this error.   Also provide the client and server versions that you are using.

**Comment by batchenoz** [comment]
server version: 
java-client version: 4.1.8

code (scala): 

object Policies {
    /** Set record ttl for write/touch operations. */
    var policy = new WritePolicy()
    policy.expiration = 60 * 60 * 24 * 90 //90 days
    val defaultWritePolicy = policy

    /** Create ordered list when list does not exist.
      * Only unique values will be added. */
    val uniqueListPolicy = new ListPolicy(ListOrder.ORDERED, ListWriteFlags.ADD_UNIQUE)
  }

def touchAndGet(key: Key, bin: String,
                  writePolicy: WritePolicy = Policies.defaultWritePolicy): Record = {
    val record = 
      aerospikeClient.operate(writePolicy, key, Operation.touch(), Operation.get(bin))
   
    monitoring.increment(s"aerospike.${key.namespace}.${key.setName}.touch")
    monitoring.increment(s"aerospike.${key.namespace}.${key.setName}.get")

    record
  }

Thanks.

**Comment by batchenoz** [comment]
Yes, the key exists and I see the ttl for that record gets updated after the call to operate()

**Comment by BrianNichols** [comment]
I'm confused.  You previously said the operate() call failed on touch()/get().  Are you now saying the operate() call succeeds?

The reason I asked for a full reproducible program (and not a code snippet) is that it greatly reduces ambiguity.  Can you just run my full test program and respond with the results?

**Comment by batchenoz** [comment]
I wrote in the previous messages that the touch operation worked and the read raised an exception.

I'll run your code and check it again.
Thank you

**Comment by batchenoz** [comment]
Your example works correctly. I'll try to figure out why my code doesn't and update if I'll find out anything relevant. Thank you very much for your help.

**Comment by batchenoz** [comment]
It turned out I had somewhere in my code a read() command before the get().
I didn't expect to get an exception every time a key was missing.
I believe that using exceptions in that way is old fashion and bad practice, but this is for another talk.
Thank you very much for your help. Closing the issue.
