### ISSUE TITLE
Change log for major-version updates.

### ISSUE THREAD

**Issue by harshvladha** [aerospike/aerospike-client-java#104]
Hi,

Where can I find the change log between major versions like 4.0 to 4.1 ?

**Comment by BrianNichols** [comment]
Release notes are located here: https://www.aerospike.com/download/client/java/notes.html

For source code changes, checkout 4.0 and 4.1 in separate repos and diff them.

**Comment by harshvladha** [comment]
Thanks @BrianNichols
