### ISSUE TITLE
Replace gnu cyrpto with Non GPL alternative

### ISSUE THREAD

**Issue by aahmed-se** [aerospike/aerospike-client-java#110]
Currently  the aerspike java client is using the gnu crypto library for base64 and RupeMD hashing.

Since it's a GPL based library packing with other systems is complicated. Would request the library be replaced with a non GPL alternative that has more flexible licensing.

https://github.com/aerospike/aerospike-client-java/search?l=Java&q=gnu&type=

**Comment by merlimat** [comment]
Hi @BrianNichols , unfortunately the interpretation of ASF is a bit different and any dependencies with GPL+exceptions are not allowed in any Apache projects. https://www.apache.org/legal/resolved.html#category-x

**Comment by BrianNichols** [comment]
That is an unfortunate interpretation.  We will investigate methods to switch RIPEMD-160/base64 implementations.  No decisions yet, just some research.

**Comment by BrianNichols** [comment]
Aerospike Java client 4.1.11 adds the ability to switch between GNU and Bouncy Castle crypto libraries at compile time.  Bouncy Castle has a [MIT-based license](https://www.bouncycastle.org/license.html).

There are now two Aerospike Java client libraries available on [Maven Central Repository](https://search.maven.org/search?q=aerospike-client).  The previously existing **aerospike-client** continues to link with GNU crypto.  The new **aerospike-client-bc** links with Bouncy Castle crypto.

To use AerospikeClient with Bouncy Castle crypto, define this dependency in your pom.xml.

```xml
    <dependency>
      <groupId>com.aerospike</groupId>
      <artifactId>aerospike-client-bc</artifactId>
      <version>4.1.11</version>
    </dependency>
```

**Comment by aahmed-se** [comment]
Thanks @BrianNichols this should work
