### ISSUE TITLE
Possibility to add circle ci integration

### ISSUE THREAD

**Issue by Aloren** [aerospike/aerospike-client-java#111]
Is it possible to enable circleci integration for this project?
It will run automatic builds for each opened pull request -- no broken code will be merged into master.

The only prerequisite for this change is: setting up aerospike-server in tests via testcontainers. I could implement this change via pr if you like the idea.

**Comment by BrianNichols** [comment]
Sure, we would accept a pull request for this.

**Comment by BrianNichols** [comment]
It has been pointed out to me that our other projects use travis (like our C client) for CI.  We would prefer a pull request using travis if possible.

**Comment by Aloren** [comment]
Ok, I will prepare pull request with embedded aerospike firstly.
Thanks

**Comment by bsideup** [comment]
@Aloren @BrianNichols just fyi: Testcontainers works perfectly fine on Travis :)
As simple as adding these two lines to the config:
```yaml
sudo: required
services:
  - docker
```

**Comment by BrianNichols** [comment]
We decided to go with our traditional approach used in our other client repositories.
