### ISSUE TITLE
Modules from "extensions" not available in public maven repo

### ISSUE THREAD

**Issue by vasilievip** [aerospike/aerospike-client-java#116]
https://github.com/aerospike/aerospike-client-java/tree/master/extensions
https://mvnrepository.com/artifact/com.aerospike

**Comment by BrianNichols** [comment]
This will be added to maven central next week.

**Comment by BrianNichols** [comment]
The aerospike-reactor-client library is now available on maven central:

https://search.maven.org/artifact/com.aerospike/aerospike-reactor-client/4.2.0/jar
