### ISSUE TITLE
aerospike-query-engine 4.2.2, 4.2.1 is not present in Maven Cental

### ISSUE THREAD

**Issue by Aloren** [aerospike/aerospike-client-java#118]
Hello!
I wanted to updated aerospike client dependecies, but was not able to find aerospike-query-engine of version 4.2.2 or 4.2.1 in [Maven Central](https://mvnrepository.com/artifact/com.aerospike/aerospike-query-engine). Looks like there is an issue with publishing this dependency.

Thanks.

**Comment by BrianNichols** [comment]
This was intentional.  aerospike-query-engine has very specific query functionality and many client releases do not affect queries at all.  If a new client release affects queries, we will release a new aerospike-query-engine.

**Comment by Aloren** [comment]
Hmm. That is not common practice in java world. Please take a look at for example very popular java libraries: [jackson](https://mvnrepository.com/artifact/com.fasterxml.jackson.core), [spring](https://mvnrepository.com/search?q=spring). All modules are released at the same time, it can be simply automated with maven-release-plugin, you also don't need to think about which modules should be released and which are not, and the most important -- you know exactly that all modules with the same version are compatible with each other. Very simple to understand and use.

**Comment by BrianNichols** [comment]
We will look into providing aerospike-query-engine for every client release (starting next client release).

**Comment by BrianNichols** [comment]
Java client 4.2.3 released (includes query-engine 4.2.3).

https://www.aerospike.com/download/client/java/4.2.3/
