### ISSUE TITLE
AeroSpike with create_only policy throws record_already_exists error even-though there is no record

### ISSUE THREAD

**Issue by anandhkumar** [aerospike/aerospike-client-java#124]
https://stackoverflow.com/questions/53813764/aerospike-with-create-only-policy-throws-record-already-exists-error-even-though

**Comment by BrianNichols** [comment]
I suggest you try Ronen's suggestion for debugging the problem.

**Comment by anandhkumar** [comment]
As per the Ronen's suggestion, we already added debug statement to print getHeader metadata , but we are seeing the fist get function return key is not there and sub-sequence CREATE_ONLY policy throws 'KEY_ALREADY_EXISTS'. What could be the issue and how we can fix this?

**Comment by rbotzer** [comment]
Please check the response in stackoverflow.
