### ISSUE TITLE
Possible crashable code

### ISSUE THREAD

**Issue by swayamraina** [aerospike/aerospike-client-java#125]
https://github.com/aerospike/aerospike-client-java/blob/134f267ece814fc2bddee540a7b98440efaab449/client/src/com/aerospike/client/Host.java#L77

If comparison to a **null** Host is made, the code can crash unexpectedly at client end.

Possible fix#1:
```java
if (null == obj) return false;
Host other = (Host) obj;
return this.name.equals(other.name) && this.port == other.port;
```

Possible fix#2:
```java
if (obj instanceof Host) {
    Host other = (Host) obj;
    return this.name.equals(other.name) && this.port == other.port;
}
return false;
```

I would love to contribute & commit this change, if it is needed.

Thanks!

**Comment by BrianNichols** [comment]
We will check for null in the next release.

**Comment by BrianNichols** [comment]
Java client 4.3.0 has been released:

https://www.aerospike.com/download/client/java/4.3.0/
