### ISSUE TITLE
Provide capability to read data from multiple clusters

### ISSUE THREAD

**Issue by s-aravind-flipkart** [aerospike/aerospike-client-java#126]
Aerospike client support to query multiple aerospike clusters i.e federated client to query multiple clusters

**Comment by BrianNichols** [comment]
I'm not so sure I understand this request.  Multiple clusters can be queried using multiple instances of AerospikeClient.

**Comment by s-aravind-flipkart** [comment]
Yes, it is possible but providing a single interface for multiple clients will allow disparate clusters to be queried. Today ES provides cross-cluster search capabilities was thinking such a thing is possible or not from aerospike
