### ISSUE TITLE
[Bug] client throws ArrayIndexOutOfBoundsException when key is too long

### ISSUE THREAD

**Issue by justinj656** [aerospike/aerospike-client-java#131]
Hi Aerospike team,

I discovered that if the key is String, and its size is too long, Aerospike client throws `ArrayIndexOutOfBoundsException`.
Is it better to throw other more meaningful exception instead?

ps: I'm using version 4.1.7.

```log
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 8192
	at com.aerospike.client.command.Buffer.stringToUtf8(Buffer.java:195)
	at com.aerospike.client.Value$StringValue.write(Value.java:574)
	at com.aerospike.client.Key.computeDigest(Key.java:315)
	at com.aerospike.client.Key.<init>(Key.java:94)
	at TryAerospike.main(TryAerospike.java:25)
```

Thank you,
Justin

**Comment by BrianNichols** [comment]
The key's maximum size is documented in javadocs for all key constructors.  The existing exception in combination with the documentation is sufficient.  From the javadocs:

> The key is converted to bytes to compute the digest. The key's byte size is limited to the current thread's buffer size (min 8KB). To store keys > 8KB, do one of the following:
>
> Set once:
>
>  ThreadLocalData.DefaultBufferSize = maxKeySize + maxSetNameSize + 1;
>
>    Or for every key:
>
>     int len = key.length() + setName.length() + 1;
>     if (len > ThreadLocalData.getBuffer().length))
>         ThreadLocalData.resizeBuffer(len);

**Comment by Aloren** [comment]
what's the problem with adding validation of input parameters? this is standard for any public api.
