### ISSUE TITLE
Connection Pool Question: How to make sure 'x' connections are always created

### ISSUE THREAD

**Issue by s-aravind-flipkart** [aerospike/aerospike-client-java#133]
Like in Jedis using GenericObjectPool there is a way to specify idle and max connections the client needs to create. Is there a similar way in java client to specify both aspects

**Comment by BrianNichols** [comment]
ClientPolicy.maxConnsPerNode sets max connections for each server node.
ClientPolicy.maxSocketIdle sets max seconds connections may remain idle in a connection pool.

**Comment by s-aravind-flipkart** [comment]
@BrianNichols Thanks for the info. This pool also includes for batch reads right.

**Comment by BrianNichols** [comment]
Yes, batch reads use a connection for each target node from the node's connection pool.

**Comment by BrianNichols** [comment]
ClientPolicy.minConnsPerNode has been supported for a while now.
