### ISSUE TITLE
Truncate failed: ERROR::last-update-time if beforeLastUpdate is null

### ISSUE THREAD

**Issue by Gr1f0n6x** [aerospike/aerospike-client-java#134]
I get this error:
`com.aerospike.client.AerospikeException: Error Code -1: Truncate failed: ERROR::last-update-time
` when i try to truncate the whole namespace using this call: `client.truncate(null, "namespace_test", null, null);`. Method's doc says that 	 

> @param beforeLastUpdate	- optional delete records before record last update time.
> If specified, value must be before the current time.
> Pass in null to delete all records in namespace/set.

If i pass some value as `beforeLastUpdate` param, then there is no errors.
Also, i'm using aerospike in docker (currently, the latest image version)

Code to reproduce:
```
public class Test {
    public static void main(String[] args) {
        ClientPolicy policy = new ClientPolicy();
        AerospikeClient client = new AerospikeClient(policy, "localhost", 3000);
        client.truncate(null, "namespace_test", null, null);
    }
}
```

Client version: `4.1.11`
Aerospike conf:

> logging {
>   console {
>     context any critical
>   }
> }
> 
> namespace namespace_test {
>   memory-size 1G      
>   storage-engine memory  
> }
> 
> network {
>   service {
>     address any
>     port 3000
> 
>   }
> 
>   heartbeat {
> 
>     address any
>     mode mesh
>     port 3002
> 
> 
>     interval 150
>     timeout 10
>   }
> 
>   fabric {
>     address any
>     port 3001
>   }
> 
>   info {
>     address any
>     port 3003
>   }
> }

The question: is this a correct behaviour or not? I'm new to aerospike and maybe i miss something.

**Comment by BrianNichols** [comment]
Server versions between 4.3.1.4 and 4.5.0.1 required a beforeLastUpdate argument and java client 4.1.11, does not provide a default.  You will need to upgrade your java client to get truncate() to work.

**Comment by Gr1f0n6x** [comment]
Oh, didn't know that. Thank you!
