### ISSUE TITLE
Add support of asynchronous index related methods 

### ISSUE THREAD

**Issue by igor-ermolenko** [aerospike/aerospike-client-java#137]
It would be great to have an asynchronous equivalent of index related methods in AerospikeClient:
createIndex(), deleteIndex() and indexExists()

**Comment by kptfh** [comment]
https://github.com/aerospike/aerospike-client-java/pulls

**Comment by BrianNichols** [comment]
Java client 4.4.8 has been released with async index support.

https://www.aerospike.com/download/client/java/4.4.8/
