### ISSUE TITLE
Provide latency metrics out of client and listener to integrate with metrics registry

### ISSUE THREAD

**Issue by vasilievip** [aerospike/aerospike-client-java#138]
Example:
https://docs.couchbase.com/java-sdk/2.7/collecting-information-and-logging.html#metric-events

```
"10.142.111.102": {
    "BINARY": {
      "GetRequest": {
        "NOT_EXISTS": {
          "metrics": {
            "percentiles": {
              "50.0": 124,
              "90.0": 199,
              "95.0": 234,
              "99.0": 489,
              "99.9": 3784
            },
            "min": 69,
            "max": 175112,
            "count": 74864,
            "timeUnit": "MICROSECONDS"
          }
        }
      },
```

**Comment by Fetsivalen** [comment]
Hi Guys,
any chance it will be considered as a part of the client?
it is a really important feature for our services all users of this client.

**Comment by BrianNichols** [comment]
We do provide latency bucket functionality in the java client benchmark application (`-latency <columns>,<range shift increment>`), but not in the client library itself.

There are no current plans to add this feature to the java client.  Latency capture could be added independently by inheriting from AerospikeClient and adding new methods (with a stopwatch timer) that call the corresponding AerospikeClient methods.

**Comment by barkanido** [comment]
We would also be very happy to have those, even as an optional feature, one can create the client with/without.

**Comment by Fetsivalen** [comment]
Hi @BrianNichols 
First of all thanks for a quick response.
When you wrote about latency bucket functionality you meant [this one](https://github.com/aerospike/aerospike-client-java/blob/master/benchmarks/src/com/aerospike/benchmarks/LatencyManagerAerospike.java)?
From what I understand that currently, your expectation is that every user of the library will implement it on their own, right?

**Comment by BrianNichols** [comment]
Yes, that one.  We may implement something like this in the long term, but if you need it now, you will need to implement it on your own.

**Comment by Aloren** [comment]
@BrianNichols can we consider contributing this feature to the aerospike-client?

**Comment by BrianNichols** [comment]
Yes. I suggest adding AerospikeClientMetrics that implements IAerospikeClient and uses AerospikeClient as a member field.

**Comment by BrianNichols** [comment]
Metrics functionality has been added to java client 7.0.0:

https://download.aerospike.com/download/client/java/notes.html#7.0.0
