### ISSUE TITLE
AerospikeClient does not play well in unit testing

### ISSUE THREAD

**Issue by sandonjacobs** [aerospike/aerospike-client-java#14]
My company is using the Java Aerospike client to connect from our jvm-based apps to various clusters. In an attempt to get good unit test coverage around our applications code, we tried to use Mockito to mock our code interaction with the AerospikeClient class. However since ALL methods of AerospikeClient are final, this is not possible without the use of PowerMockito or some other "more brute force" framework - which usually points out code-smell (IMHO).

So my issue is more of a question as to WHY all of these methods are final?

Thanks in advance...

**Comment by traviskaufman** [comment]
+1. We're having an extremely difficult time working with the client in our tests for this exact same reason. Perhaps if you want those optimizations, you could declare all of the methods in an interface and then actually implement them as final methods in an implementation class? That way tools like mockit [scalamock](http://scalamock.org/) could use the interface but in the production code you'd get the benefit of the optimized `final` methods from the implementation class.

**Comment by BrianNichols** [comment]
We are planning to add IAerospikeClient and IAsyncClient interfaces that should be more mock friendly.  This will be available in the next release.

**Comment by kennethjor** [comment]
FWIW in our infrastructure we use a wrapper class which handles talking to Aerospike and decoding everything to the correct objects. Having this class means for unit testing we can simply cut out the Aerospike library altogether. That might be a workaround until an interface is available.

**Comment by sandonjacobs** [comment]
We did the same thing, putting a layer of abstraction between our code and the Aerospike client to better accommodate testing. Once the next release is available it seems will may be able to rip this out.

**Comment by traviskaufman** [comment]
same here, but we also wanted to test the wrapper _itself_, so we still needed to figure out how to mock Aerospike.

Since we're using scala, we actually wound up creating a type class containing the Aerospike client methods we needed, and had our Aerospike service require that

```scala
object ASClientLike {
  implicit def aerospikeClientIsASClientLike(as: AerospikeClient): ASClientLike = new ASClientLike {
    def get(policy: Policy, key: Key): Record = as.get(policy, key)
  }
}

trait ASClientLike {
  def get(policy: Policy, key: Key): Record
}

object AerospikeService {
  import ASClientLike._

  def apply(client: ASClientLike, namespace: String)(implicit ec: ExecutionContext): AerospikeService =
    new AerospikeServiceImpl(client, namespace)(ec)
    
  private class AerospikeServiceImpl(client: ASClientLike, namespace: String)(implicit val ec: ExecutionContext) extends AerospikeService
}

trait AerospikeService {
  def client: ASClientLike

  def namespace: String
  
  def get[T](setName: String, keyName: KeyName, binName: String): Future[Option[T]] = Future {
    val key = new Key(namespace, setName, keyName)
    Option(client.get(null, key)) flatMap {
      rec => Option(rec.getValue(binName)) map { _.asInstanceOf[T] }
    }
  }
}
``` 

So now we can use it in production

```scala
import ASClientLike._

val client = new AerospikeClient(policy, clusterNodes: _*)
val aerospike = AerospikeService(client, "namespace")

// ...
```

as well as in tests (we use [scalamock](http://scalamock.org/) for mocking)
```scala
class AerospikeServiceSpec extends WordSpec 
    with Matchers with OneInstancePerTest MockFactory {
  val fakeClient = mock[ASClientLike]
  val service = AerospikeService(fakeClient, "namespace")

  // ...
}
```

It's a lot of boilerplate, but that also allows us to keep our implementation super flexible without altering any public APIs

**Comment by BrianNichols** [comment]
Java client 3.0.34 has been released which includes IAerospikeClient and IAsyncClient.

**Comment by maverickgautam** [comment]
https://github.com/maverickgautam/Aerospike-unit/

This is a Java wrapper over actual Aerospike Server which can be used for unit + Integration Testing . 
Pom is having some issue i am fixing it ASAP , please let me know if you want to use i can do it urgently . Reachable at kunal.gautham@gmail.com
