### ISSUE TITLE
AerospikeException is not serializable

### ISSUE THREAD

**Issue by jrumbinas** [aerospike/aerospike-client-java#141]
`Throwable` class implements `Serializable`, thus one would expect `AerospikeException` to be serializable as well.  For one, it used to be serializable before `node` and `policy` fields were added.

Could we at least flag these fields as transient? I personally prefer loosing some exception message details to throwing NotSerializableException.

**Comment by BrianNichols** [comment]
Yes, the transient keyword will be added to `node` and `policy` in `AerospikeException` in the next client release.

**Comment by jrumbinas** [comment]
Will it make it to 4.4.6?

**Comment by BrianNichols** [comment]
Yes.
