### ISSUE TITLE
Returned type of the same operation expands from Integer to Long type

### ISSUE THREAD

**Issue by mpryahin** [aerospike/aerospike-client-java#15]
Hello,
I'm trying to use increment and get operation like the following:

    Record record = client.operate(
            null,
            new Key("foo", "bar", "keyValue"),
            Operation.add(new Bin("test", 1L)),
            Operation.get("test")
        );

Returned Record contains entry with Integer value type.  Everything goes well until Integer overflows.
So after integer overflows like the following:

    record = client.operate(
            null,
            new Key("foo", "bar", "keyValue"),
            Operation.add(new Bin("test", Integer.MAX_VALUE)),
            Operation.get("test")
        );
Returned Record will contain entry with Long value type.

In my opinion it's a little bit confusing and makes me write redundant code in a "switch case" manner.
I think it will be much more better to support the single returned type for such kind of operations.

**Comment by BrianNichols** [comment]
I agree.  The next java client release will always return numbers as longs (64-bit).
