### ISSUE TITLE
Why reactor client is gone in 4.11? 

### ISSUE THREAD

**Issue by STRRL** [aerospike/aerospike-client-java#164]
Hi, I found that entire `extension` directory is gone with release tag 4.11, also include reactor client.

Is it not maintenance anymore? Or be just moved to another repo?

**Comment by BrianNichols** [comment]
Extension projects were moved to a separate repo (https://github.com/aerospike-community/aerospike-client-java-extensions).  See 4.11 release notes:

https://www.aerospike.com/download/client/java/notes.html#4.4.11
