### ISSUE TITLE
build fails in javadoc generation step

### ISSUE THREAD

**Issue by kuldeepiitg** [aerospike/aerospike-client-java#168]
~/W/r/aerospike-client-java $: mvn -f client/pom.xml javadoc:javadoc                                                                                                          Fri Jul 24 11:47:27 2020
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------< com.aerospike:aerospike-client >-------------------
[INFO] Building aerospike-client 4.4.15
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] >>> maven-javadoc-plugin:2.9.1:javadoc (default-cli) > generate-sources @ aerospike-client >>>
[INFO] 
[INFO] <<< maven-javadoc-plugin:2.9.1:javadoc (default-cli) < generate-sources @ aerospike-client <<<
[INFO] 
[INFO] 
[INFO] --- maven-javadoc-plugin:2.9.1:javadoc (default-cli) @ aerospike-client ---
.
.
.
.
.
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.9.1:javadoc (default-cli) on project aerospike-client: An error has occurred in JavaDocs report generation: 
[ERROR] Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in http://docs.oracle.com/javase/7/docs/api/ are in the unnamed module.
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/cdt/MapPolicy.java:46: warning - invalid usage of tag <
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/cdt/MapPolicy.java:47: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/cdt/MapWriteFlags.java:21: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/cdt/MapWriteMode.java:21: warning - invalid usage of tag <
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/cdt/MapWriteMode.java:22: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/IAerospikeClient.java:515: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/Key.java:70: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/Key.java:106: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/Key.java:142: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/operation/BitOperation.java:227: warning - invalid usage of tag <
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/operation/BitOperation.java:255: warning - invalid usage of tag <
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/operation/BitOperation.java:283: warning - invalid usage of tag <
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/operation/HLLOperation.java:28: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/policy/BatchPolicy.java:43: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/policy/BatchPolicy.java:60: warning - invalid usage of tag <
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/policy/Policy.java:27: warning - invalid usage of tag <
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/policy/Policy.java:69: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/policy/Policy.java:173: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/policy/Policy.java:267: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/policy/QueryPolicy.java:29: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/policy/QueryPolicy.java:67: warning - invalid usage of tag <
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/policy/QueryPolicy.java:89: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/policy/RecordExistsAction.java:38: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/policy/RecordExistsAction.java:45: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/policy/ScanPolicy.java:32: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/policy/ScanPolicy.java:41: warning - invalid usage of tag <
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/policy/ScanPolicy.java:42: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/policy/ScanPolicy.java:85: warning - invalid usage of tag <
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/policy/ScanPolicy.java:115: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/policy/WritePolicy.java:64: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/policy/WritePolicy.java:65: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/policy/WritePolicy.java:67: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/query/PredExp.java:212: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/query/PredExp.java:219: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/query/PredExp.java:226: warning - invalid usage of tag <
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/query/PredExp.java:233: warning - invalid usage of tag <
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/query/PredExp.java:152: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/query/PredExp.java:212: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/query/PredExp.java:219: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/query/PredExp.java:226: warning - invalid usage of tag <
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/query/PredExp.java:233: warning - invalid usage of tag <
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/query/PredExp.java:331: warning - invalid usage of tag <
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/query/PredExp.java:346: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/query/PredExp.java:362: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/query/Statement.java:119: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/query/Statement.java:129: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/query/Statement.java:129: warning - invalid usage of tag <
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/query/Statement.java:129: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/query/Statement.java:129: warning - invalid usage of tag <
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/query/Statement.java:148: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/util/ThreadLocalData.java:47: warning - invalid usage of tag <
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/util/ThreadLocalData.java:47: warning - invalid usage of tag <
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/query/PredExp.java:212: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/query/PredExp.java:219: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/query/PredExp.java:226: warning - invalid usage of tag <
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/query/PredExp.java:233: warning - invalid usage of tag <
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/query/PredExp.java:212: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/query/PredExp.java:219: warning - invalid usage of tag >
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/query/PredExp.java:226: warning - invalid usage of tag <
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/query/PredExp.java:233: warning - invalid usage of tag <
[ERROR] /Users/kuldeep/Work/repos/aerospike-client-java/client/src/com/aerospike/client/util/ThreadLocalData.java:47: warning - invalid usage of tag <
[ERROR] 
[ERROR] Command line was: /usr/local/Cellar/openjdk/13.0.2+8_2/libexec/openjdk.jdk/Contents/Home/bin/javadoc @options @argfile
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/Users/kuldeep/Work/repos/aerospike-client-java/client/apidocs' dir.
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by BrianNichols** [comment]
Which java version are you using?

I see these messages:
```
[ERROR] Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in http://docs.oracle.com/javase/7/docs/api/ are in the unnamed module.
[ERROR] Command line was: /usr/local/Cellar/openjdk/13.0.2+8_2/libexec/openjdk.jdk/Contents/Home/bin/javadoc @options @argfile
```
If you are using version 7, our minimum supported version is 8.
If you are using version 13, then further investigation is needed.

**Comment by BrianNichols** [comment]
A newer version of javadoc was generating errors.  All javadoc errors and some warnings are now fixed.  The remaining javadoc "tag missing" warnings are now suppressed.
