### ISSUE TITLE
Support kqueue netty native transport

### ISSUE THREAD

**Issue by SamBarker** [aerospike/aerospike-client-java#175]
Our team has a mix of Linux and Macos users and we reently tried to enable support for native transport in our apps using netty. 

However this failed mysteriously for all the Macos users when trying to run our aerospike tests. After a lot of digging we realised that it was because netty was able to load the native transport driver in our project (we have the correct dependency in our pom) we detected that kqueue was available and configured the eventloop group we provided to the aerospike client as a `KQueueEventLoopGroup`.  This doesn't work due to `NettyCommand` specifying the channel as `NioSocketChannel.class`.

**Comment by BrianNichols** [comment]
Your pull request has been accepted.  It will appear in the next release of the java client.
