### ISSUE TITLE
Missing alternative to former MaxCommandAction.BLOCK

### ISSUE THREAD

**Issue by monrealis** [aerospike/aerospike-client-java#181]
I see that this no longer works https://www.aerospike.com/apidocs/java/com/aerospike/client/async/MaxCommandAction.html#BLOCK. Is there an alternative in you client? I cannot find any.

**Comment by monrealis** [comment]
I can use Semaphore of course, but is there anything in a client?

**Comment by BrianNichols** [comment]
BLOCK still works, but I would recommend using DELAY instead.

**Comment by monrealis** [comment]
How can it work if there is no such class?
![image](https://user-images.githubusercontent.com/2280367/110182498-90948e80-7e15-11eb-84c9-08cc5b319b18.png)

**Comment by BrianNichols** [comment]
MaxCommandAction is an enum.

**Comment by BrianNichols** [comment]
Ok, now I understand your issue.  MaxCommandAction only exists in the C# client.  You are trying to find MaxCommandAction in the java client which does not exist.

In the java client, async command throttling is configured via [EventPolicy](https://www.aerospike.com/apidocs/java/com/aerospike/client/async/EventPolicy.html).

**Comment by monrealis** [comment]
> 
> 
> MaxCommandAction is an enum.

Enum is a class in Java.

**Comment by monrealis** [comment]
Is there a way to configure event policy the same like it used to be with BLOCK? My conjecture is that no.

**Comment by BrianNichols** [comment]
BLOCK can lead to deadlock when a new async command is initiated from a callback in the eventloop thread.  Any blocking should be performed outside of the eventloop.

**Comment by monrealis** [comment]
With BLOCK I was able to fulfill use case: write a bunch of records, waiting as long as needed, but not exceeding some load parameters. Now there is no way to do it.

**Comment by BrianNichols** [comment]
That use case is best supported by the sync API.
