### ISSUE TITLE
Support getCount in HLLValue

### ISSUE THREAD

**Issue by yarosman** [aerospike/aerospike-client-java#188]
For example I want retrieve 30 records with bins ‘сlicks’, ‘shows’, ‘uniques_hll’. 
If I use batch request I can retrieve ‘clicks’, ‘shows’ and raw uniques_hll HLLValue. 
And after that for each key I have to execute `operate` HLLOperation.getCount additionally. 
Is it possible to add supporting  getCount for HLLValue?

**Comment by kportertx** [comment]
Same answer as I gave here: https://discuss.aerospike.com/t/hyperloglog-getcount-supports-in-batch-request/8386.

**Comment by BrianNichols** [comment]
Adding batch read expressions that could perform the HLL getCount() on the server side with results being returned with the bins is something that has been discussed, but it's not currently on our roadmap.  There is no guarantee if/when this functionality is implemented.
