### ISSUE TITLE
Getting "basic scan got unsupported old scan options"

### ISSUE THREAD

**Issue by monrealis** [aerospike/aerospike-client-java#194]
We get "Jul 13 2021 10:48:58 GMT: WARNING (scan): (scan.c:681) basic scan got unsupported old scan options" on the server side and "Error Code 16: Unsupported Server Feature com.aerospike.client.AerospikeException: Error Code 16: Unsupported Server Feature" on the client side after upgrading server to  5.6.0.7.

Is it possible to somehow query the server from aerospike java client 3.* or 4.*? What's the oldest version that would work? Is there some workaround to avoid this issue?

**Comment by monrealis** [comment]
I guess it's 4.4.16 and commit is 0ecfab2bbe16517d2387699bb507d1686d9d5fb2.

**Comment by monrealis** [comment]
Seems to be working with 4.4.10 and not working with 4.4.9.

**Comment by BrianNichols** [comment]
The newer servers stopped supporting scan priority and scan percent fields. Java client 4.4.9 always sends these fields on scans, but 4.4.10 only sends those fields when scan priority or scan percent are not the defaults.

Java client 5.1.0 removed those scan fields on the client side. See https://docs.aerospike.com/docs/client/java/usage/incompatible.html

**Comment by monrealis** [comment]
Funny thing: I did not use scan priorities, I did not use scan percent fields and I did not use scans at all (I used queries, which got executed as scans).

**Comment by monrealis** [comment]
Thanks for explanation, I saw everything in code, just wanted to confirm.

**Comment by monrealis** [comment]
Tell me please if those scan options are so unimportant that they can be ignored on the client side, why can't they be ignored on the server side? :)

**Comment by BrianNichols** [comment]
Those scan options were eventually removed on the client side after the server removed them.  You are using an older client with a newer server, which sometimes causes gaps like this when both client and server are quickly evolving.

**Comment by monrealis** [comment]
I understand that. But why fail on the server side instead of ignoring?

**Comment by BrianNichols** [comment]
I do not make those decisions.  I think the best solution for you is to create a new branch from the your desired client version and modify Command.setScan() and Command.setQuery() to not send the SCAN_OPTIONS field.  I can assist with this if you choose this path.

**Comment by monrealis** [comment]
It's not related to this single issue, but when designing your newer version of client, take a look and how they did in JDBC. It's compatible for >20 years already and it will be compatible for > 30 years more.
