### ISSUE TITLE
Aerospike fetch time is too high when used with JRE-11

### ISSUE THREAD

**Issue by JimmyWe11s** [aerospike/aerospike-client-java#195]
We are observing significantly higher fetch times when running the application with JRE-11.
JRE version: jre-11.0.11
Aerospike-client version: 5.1.4

Below is a comparison graph of fetch times:

![aerospike-comparison](https://user-images.githubusercontent.com/58737407/126456990-69e2f644-36df-4979-8741-a454d44b54b1.jpg)

Below is cpu profiling output of the application running with JRE-11:

![hotspots](https://user-images.githubusercontent.com/58737407/126474535-72ee7eb6-6e28-4f7a-80f0-ea05b9976505.jpg)

**Comment by BrianNichols** [comment]
Are you using OracleJDK 11 or OpenJDK 11?  Can you try with both and see if there is a difference?

**Comment by JimmyWe11s** [comment]
Used OpenJDK 11 so far.
As suggested, will also try with OracleJDK 11 and update results here.
