### ISSUE TITLE
Fire and Forget

### ISSUE THREAD

**Issue by evolvednight** [aerospike/aerospike-client-java#205]
The meaning of fire and forget in async client is when do the async call and not care about the results?  Will the client confirm the result?  
Now if something goes wrong with a async fire and forget put call, I assume that it will not give me an error.

**Comment by BrianNichols** [comment]
If the async command fails to queue to the eventloop (unlikely), an exception will be thrown.  If the async command is queued to the eventloop without a listener, there is no listener to send an error or a result.
