### ISSUE TITLE
Streaming support for batch operations

### ISSUE THREAD

**Issue by dr3s** [aerospike/aerospike-client-java#208]
The batch API returns arrays which requires full responses before the client can start processing them.  It would be nice to use the reactive interfaces and support full streaming.

**Comment by BrianNichols** [comment]
There are async batch get methods that support streaming records as they are received from server nodes.

`public final void get(EventLoop eventLoop, RecordSequenceListener listener, BatchPolicy policy, Key[] keys, String... binNames)
`

Also, we have a reactive java client: https://github.com/aerospike/aerospike-client-java-reactive

**Comment by dr3s** [comment]
Thanks, must be my misunderstanding.
