### ISSUE TITLE
View screenshot link is broken

### ISSUE THREAD

**Issue by DhiralKaniya** [aerospike/aerospike-client-java#217]
Hi Team, 

Trying to see "View screenshot" under the Run scripts section in example page, but it seems broken. 

Page link:- https://github.com/aerospike/aerospike-client-java/tree/master/examples
Refer README.md

Attached link:- http://www.aerospike.com/docs/client/java/assets/java_example_screen.png

**Comment by BrianNichols** [comment]
Thanks for finding this. The link has been removed in our stage branch.
