### ISSUE TITLE
Add RetryListener

### ISSUE THREAD

**Issue by echatman-ias** [aerospike/aerospike-client-java#228]
Possibly a duplicate of https://github.com/aerospike/aerospike-client-java/issues/114
I'm hoping to log a message and increment a counter every time a retry occurs.

**Comment by BrianNichols** [comment]
RetryListener has not been implemented.  If maxRetries is reached, AerospikeException does include a count of attempts (initial attempt + retries).

**Comment by BrianNichols** [comment]
We have not committed to this functionality, but we would like to get feedback on an interface definition. Are you looking for an indication that a retry will take place or do you want a callback when a node error occurred or something else?

Here are some possible interfaces:

```java
public interface RetryListener {
    public void onRetry(Node oldNode,  Node newNode);
}

public interface ErrorListener {
    public void onError(Node node, Throwable t);  // Add other arguments?
}
```

**Comment by echatman-ias** [comment]
I want to know about an error that is being retried so I can log the error & the fact that it will be retried.
So both of those possible interfaces would need at least one more argument:

```
public interface RetryListener {
    public void onRetry(Node oldNode, Node newNode, Throwable t);
}

public interface ErrorListener {
    public void onError(Node node, Throwable t, boolean willBeRetried);
}
```

**Comment by BrianNichols** [comment]
Client metrics is on our roadmap. These metrics will include periodic latency and error counts for all node command attempts (including retries). Client metrics will eventually be implemented instead of a RetryListener.

**Comment by echatman-ias** [comment]
That sounds great, that's all I wanted a RetryListener for anyway. Is there a ticket for that I can follow?

**Comment by BrianNichols** [comment]
Not yet.  The project needs to be scheduled first.

**Comment by BrianNichols** [comment]
@echatman-ias: Metrics functionality has been added to java client 7.0.0. "retryCount" is now available in both enableMetrics() and getClusterStats().  "retryCount" is a running total of command retries since the AerospikeClient instance was created.

https://download.aerospike.com/download/client/java/notes.html#7.0.0
