### ISSUE TITLE
Scan Job Priority

### ISSUE THREAD

**Issue by prepor** [aerospike/aerospike-client-java#23]
Hi!

How i can set priority for new background scan job? There is for C client for example: http://www.aerospike.com/apidocs/c/d1/dc3/structas__scan.html#ab6b0b8a77c04f8eeb67771589338fae7

**Comment by BrianNichols** [comment]
Set "WritePolicy.priority" and call:

	public final ExecuteTask execute(
		WritePolicy policy,
		Statement statement,
		String packageName,
		String functionName,
		Value... functionArgs
	) 

Note that the priority is only used on the server if there are no query filters (i.e. converted to scan).

**Comment by prepor** [comment]
Oh, sorry, I missed it in superclass (Policy). Thank you!
