### ISSUE TITLE
Node name is null

### ISSUE THREAD

**Issue by jkvargas** [aerospike/aerospike-client-java#268]
Hi,
When trying to connect to an aerospike instance I am getting "cause":"com.aerospike.client.AerospikeException$Connection: Error -8: Failed to connect to [3] host(s): some_host_address 3000 Error -3: Node name is null"

The clear to me what I am missing.
Can you guys give me some tips? :)

**Comment by BrianNichols** [comment]
After the initial connection to a server node, the client requests the node name from the node. In this case, the server is not returning a valid node name.  Try the following command which runs independently of the java client:

```
asinfo -h <some_host_address> -v node
```

If there is no response,  the server is not configured correctly.
