### ISSUE TITLE
duplicate node name may be added to Cluster's node array

### ISSUE THREAD

**Issue by uohzoaix** [aerospike/aerospike-client-java#27]
why Node class overwrite equals() and hashCode() methods,but in Cluster class use List to store nodes?i think List should be converted to Set.

**Comment by BrianNichols** [comment]
Duplicate node names are checked before adding to cluster's node array.

**Comment by uohzoaix** [comment]
sorry,i cann't see that logic,when add node's friends,there use Host to judge the two is same or not,so in my scene,there could be happen:cluster node's:[BB900C9B4614BB7 180.97.11.172:3000, BB900C900000065 180.97.11.173:3000, BB900C900000065 192.168.1.173:3000]

**Comment by uohzoaix** [comment]
yes,i see that:
private final List<Node> findNodesToAdd(List<Host> hosts) {
		List<Node> list = new ArrayList<Node>(hosts.size());

		for (Host host : hosts) {
			try {
				NodeValidator nv = new NodeValidator(this, host);
				System.out.println("nodes arr:" + Arrays.toString(nodes));
				Node node = findNode(nv.name);

				if (node != null) {
					// Duplicate node name found.  This usually occurs when the server 
					// services list contains both internal and external IP addresses 
					// for the same node.  Add new host to list of alias filters
					// and do not add new node.
					node.referenceCount++;
					node.addAlias(host);
					aliases.put(host, node);
					continue;
				}
				node = createNode(nv);
				list.add(node);
			} catch (Exception e) {
				if (Log.warnEnabled()) {
					Log.warn("Add node " + host + " failed: " + Util.getErrorMessage(e));
				}
			}
		}
		return list;
but when add a node to list,there won't add this node to nodes array,so when add a same name node, in the findNode method it will return null too.

**Comment by BrianNichols** [comment]
If the node has a duplicate name, it will not be added to the cluster.  Nodes with the same name and different IPs are considered the same node.  The IP is simply added to the existing node's list of aliases.
