### ISSUE TITLE
java.lang.NullPointerException in AerospikeClient.put()

### ISSUE THREAD

**Issue by VitalyOrbit** [aerospike/aerospike-client-java#290]
Hi.
I get a null exceptions in the
```
public final void put(EventLoop eventLoop, WriteListener listener, WritePolicy policy, Key key, Bin... bins)
```
Instance of AerospikeClient created with HOST and PORT parameters.
Call the .put() method with "null" as the eventLoop parameter.
In such case this condition is uses:
```
// aerospike-client-java/client/src/com/aerospike/client/AerospikeClient.java:502
if (eventLoop == null) {
	eventLoop = cluster.eventLoops.next();
}
```

Versions:
com.aerospike.client: 6.3.0
aerospike server: 6.3.0.8

Is this bug or I need to pass additional data?

I just updating a service where the 3.1.6 version was used with this method:
```
public final void put(WritePolicy policy, Key key, Bin... bins)
```

**Comment by BrianNichols** [comment]
Did you set `ClientPolicy.eventLoops` and pass this policy to the AerospikeClient constructor?

See https://developer.aerospike.com/client/async

**Comment by VitalyOrbit** [comment]
> Did you set `ClientPolicy.eventLoops` and pass this policy to the AerospikeClient constructor?
> 
> See https://developer.aerospike.com/client/async

No, just `new AerospikeClient("localhost", 3000);`

**Comment by BrianNichols** [comment]
Yes, if you want to run async commands.

**Comment by VitalyOrbit** [comment]
Got it, thank you.
