### ISSUE TITLE
Bin doesn't override hashcode

### ISSUE THREAD

**Issue by daniel-siegmann-aol** [aerospike/aerospike-client-java#30]
The class [`com.aerospike.client.Bin`](https://github.com/aerospike/aerospike-client-java/blob/master/client/src/com/aerospike/client/Bin.java) overrides equals, but not hashcode. This leads to incorrect behavior when instances are used in hash-based structures (such as `HashMap`).

**Comment by BrianNichols** [comment]
We will implement hashcode on Bin in the next release.

**Comment by BrianNichols** [comment]
Client released.

**Comment by daniel-siegmann-aol** [comment]
Thank you for this, 31, and 32. These fixes will be helpful.
