### ISSUE TITLE
Setters for Spring

### ISSUE THREAD

**Issue by nstinianskiy** [aerospike/aerospike-client-java#300]
https://github.com/aerospike/aerospike-client-java/blob/c0f6ebd06b5e357b04e95e2547bf845c9113ee6c/client/src/com/aerospike/client/async/EventPolicy.java#L22C8-L22C8

It would be cool if we could set any policy with spring's `@ConfigurationProperties`. But it requires setters to set everything up.

So currently I can't do something like:
```
 @Bean
    @ConfigurationProperties(prefix = "aerospike.event-loops.event-policy")
    EventPolicy eventPolicy() {
        return new EventPolicy();
    }
```

**Comment by BrianNichols** [comment]
Setters have been added in java client 7.2.1: https://download.aerospike.com/download/client/java/notes.html#7.2.1
