### ISSUE TITLE
Filter.range Javadoc doesn't specify inclusive or exclusive

### ISSUE THREAD

**Issue by daniel-siegmann-aol** [aerospike/aerospike-client-java#31]
The javadoc comments on `com.aerospike.client.query.Filter.range` (two methods) don't specify whether the `begin` and `end` parameters are inclusive or exclusive. Assuming the wrong meaning is an easy way to introduce subtle bugs into an application.

**Comment by BrianNichols** [comment]
We will fix comments in next release.

**Comment by BrianNichols** [comment]
Client released.
