### ISSUE TITLE
Filter doesn't override equals and hashcode

### ISSUE THREAD

**Issue by daniel-siegmann-aol** [aerospike/aerospike-client-java#32]
It would save me a whole bunch of lines of code in my unit tests if `com.aerospike.client.query.Filter` overrode `equals` and `hashcode`.

**Comment by daniel-siegmann-aol** [comment]
Actually, I can't write assertions against filters at all, because there's no way to access most of the fields. This means I can't write a unit test which verifies I'm executing a statement with the correct filters. Maybe I could use the write method, but that's a poor option.

**Comment by BrianNichols** [comment]
We will implement hashcode and equals on Filter in the next release.

**Comment by BrianNichols** [comment]
Client released.
