### ISSUE TITLE
Parameter Error when making Aerospike Query with multiple equal filters

### ISSUE THREAD

**Issue by traviskaufman** [aerospike/aerospike-client-java#33]
I am using version 3.1.2 of the client and am trying to make a query which contains the following code

```java
Statement stmt = new Statement();
stmt.setNamespace("ns");
stmt.setSetName("set");
stmt.setFilters( Filter.equal("foo", "someFoo"), Filter.equal("bar", "someBar") );

RecordSet rs = asClient.query(null, stmt);
while (rs.next()) {
  // etc..
}
```

So the corresponding aql would be something like

```sql
SELECT * FROM ns.set WHERE foo = 'someFoo' AND bar = 'someBar'
```

Both `foo` and `bar` have a secondary index and the corresponding aql statement works as expected. There's also nothing in the logs regarding any indication of any error. When I only use one filter, the query works fine.

However, when I execute that statement and try and retrieve the records I get an `AerospikeException` saying `Error Code 4: Parameter Error`. 

I could not find [anything in the Java Client Documentation](http://www.aerospike.com/docs/client/java/usage/query/query.html) or [in the JavaDocs](http://www.aerospike.com/apidocs/java/) about this issue. The only thing I could find was a [response to a question](https://discuss.aerospike.com/t/error-code-4-parameter-error/275) from almost a year ago saying that multiple equal filters were not supported. I also couldn't find a changelog between clients so I'm not sure if this is still the case. If it's not the case, is there any way I can get more visibility into what it is I'm doing wrong? If it _is_ still the case, could you maybe please make that fact more apparent in the documentation?

**Comment by BrianNichols** [comment]
Unfortunately, multiple filters are still not support by the server.  The client was written with the assumption that multiple filters would eventually be supported, but it did not happen.

We will update the javadocs in the next java client release.

**Comment by traviskaufman** [comment]
hmm do any of the other aerospike clients support this? I'd be happy to work on the feature for the Java client. We use Aerospike extensively and this functionality would really help simplify some of our code.

**Comment by wchu-citrusleaf** [comment]
This can alternatively be done currently on the server side via the aggregation framework. See 
the example: http://www.aerospike.com/community/labs/query_multiple_filters.html
