### ISSUE TITLE
Why are the InputStream and OutputStream in the connection not wrapped with Buffered?

### ISSUE THREAD

**Issue by funky-eyes** [aerospike/aerospike-client-java#361]
https://github.com/aerospike/aerospike-client-java/blob/ad1b533ebaa6dc42b2265eedfa29d3b99589dfdd/client/src/com/aerospike/client/cluster/Connection.java#L77
```
				in = socket.getInputStream();
				out = socket.getOutputStream();
```
change to
```
					in = new BufferedInputStream(socket.getInputStream());
					out = new BufferedOutputStream(socket.getOutputStream());
```
Would this change help improve I/O performance?

**Comment by BrianNichols** [comment]
I doubt it. The client already buffers each command and sends that buffer to the socket.

**Comment by funky-eyes** [comment]
> I doubt it. The client already buffers each command and sends that buffer to the socket.

I am also confused. Currently, I only see BufferedInputStream being used in MultiCommand

**Comment by funky-eyes** [comment]
Are you referring to the dataBuffer? That does have an effect, but in this case, connection#write is essentially a writeAndFlush action.

Also, there's another question: doesn't OutputStream require a buffer?

**Comment by BrianNichols** [comment]
Yes, I'm referring to the dataBuffer. Writing the complete command to the dataBuffer and sending that dataBuffer to the socket's unbuffered output stream minimizes latency.  Adding an additional buffered stream will delay sending of the complete command until the stream buffer is full.  Thus, command latency would suffer.

No. The socket's OutputStream does not require a buffer.

**Comment by funky-eyes** [comment]
> Yes, I'm referring to the dataBuffer. Writing the complete command to the dataBuffer and sending that dataBuffer to the socket's unbuffered output stream minimizes latency. Adding an additional buffered stream will delay sending of the complete command until the stream buffer is full. Thus, command latency would suffer.
> 
> No. The socket's OutputStream does not require a buffer.

I understand now, thank you for your reply
