### ISSUE TITLE
removeUdf method for AerospikeClient is missing

### ISSUE THREAD

**Issue by Ganet** [aerospike/aerospike-client-java#37]
Not sure if its an issue or intended but removeUdf method in the API is missing. I'm currently using a self-made tool to generate lua UDFs and register them in Aerospike, but I cannot remove them in a "development way" unless I do it manually.

This operation already exists in Ruby and Go clients and I think it is odd to have inconsistency for different language bindings (http://www.aerospike.com/docs/client/go/usage/udf/remove.html and http://www.aerospike.com/docs/client/ruby/usage/udf/remove.html) even more given the fact I can register indexes and UDFs but cannot remove them.

EDIT: C bindings also have remove options http://www.aerospike.com/docs/client/c/usage/udf/register.html

**Comment by BrianNichols** [comment]
removeUdf() will added in the next release.

**Comment by Ganet** [comment]
Thank you for your fast answer and thank you for your help!

**Comment by Ganet** [comment]
I'm reopening the issue until it gets fixed just as a small reminder. Sorry for closing it earlier.

**Comment by Ganet** [comment]
I have just realised the new removeUdf() method is actually available. I did not see it in http://www.aerospike.com/download/client/java/notes.html so I thought it wasn't.

My mistake, I'm closing the issue right now.

Thank you for your support.
