### ISSUE TITLE
Support set udf path

### ISSUE THREAD

**Issue by chzhuo** [aerospike/aerospike-client-java#39]
there is a function to set udf path in aerospike-client-c,but i cann't find the same function in aerospike-client-java.

it seem that not allow to modify the lua path
![image](https://cloud.githubusercontent.com/assets/10919124/8694592/8819a166-2b12-11e5-8de1-39a96d518627.png)

**Comment by BrianNichols** [comment]
Set LuaConfig.SourceDirectory = "myluadirectory";
