### ISSUE TITLE
Unable to reconnect

### ISSUE THREAD

**Issue by iveeshal** [aerospike/aerospike-client-java#40]
Hi,

Suppose one of my aerospike node is down. In that case the java client should be able to reconnect when the node is up.Presently the client keeps the old connection object cached .Please let me know if we can approach to this problem somehow.

**Comment by BrianNichols** [comment]
If a node goes down, the client will receive notification from the server within 1 second.  When that happens, the node's cached connections are dropped and the node is removed from the client map.

When the cluster adds the node (after restart), the node's connection pool will be populated with new connections.
