### ISSUE TITLE
Get all indexes

### ISSUE THREAD

**Issue by sparkpool** [aerospike/aerospike-client-java#42]
Can we have some method in aerospike java client which can provide us all indexes present in all namespaces or in a particular namespace.

**Comment by BrianNichols** [comment]
Index information can be obtained in the following ways.

* aql
   \> show indexes
   \> stat index <namespace> <index name>

* asinfo 
   asinfo -v 'sindex-list:' 
   asinfo -v 'sindex/\<namespace\>'
   asinfo -v 'sindex/\<namespace\>/\<index name\>'

* java client
  Node node = client.getNodes()[0];
  String result = Info.request(node, "sindex-list:");
  result = Info.request(node, "sindex/" + namespace);
  result =  Info.request(node, "sindex/" + namespace + '/' + indexName);

  The result is a single string which needs to be parsed for individual index information.  We do accept code contributions that provide parsing of these result strings into more user-friendly classes.

**Comment by sparkpool** [comment]
Thanks Brian for your help !!!!
