### ISSUE TITLE
Null pointer in LList exists

### ISSUE THREAD

**Issue by ameykpatil** [aerospike/aerospike-client-java#46]
This is the exists method. When corresponding key or llist is missing in Aerospike, list object at the 2nd line is null & hence list.size() at 3rd line throws Null Pointer exception.
```java
public List<Boolean> exists(List<Value> keyValues) throws AerospikeException {
		List<?> list = (List<?>)client.execute(policy, key, PackageName, "exists", binName, Value.get(keyValues));
		List<Boolean> target = new ArrayList<Boolean>(list.size());
		
		for (Object obj : list) {
			target.add(Util.toBoolean(obj));
		}
		return target;
	}
```
Not sure if similar issues are there for other methods too.

**Comment by BrianNichols** [comment]
This will be fixed in the next release.
