### ISSUE TITLE
Provide a way to change default policy when using IAerospikeClient/IAsyncClient

### ISSUE THREAD

**Issue by vkorenev** [aerospike/aerospike-client-java#48]
**Scenario:** I want to put a value using client's default write policy, but I want to set expiration time for the record. If I use the `AerospikeClient` class I can do that like this:
```java
AerospikeClient client = getClient();
WritePolicy policy = new WritePolicy(client.writePolicyDefault);
policy.expiration = 10;
client.put(policy, key, bin);
```
But I cannot access `writePolicyDefault` if I use the `IAerospikeClient` interface.
Please either create getters for default policies in the interfaces or provide another way to apply a modified default policy for an operation.

**Comment by BrianNichols** [comment]
We will added getters for the default policies in the interfaces in the next release.

**Comment by BrianNichols** [comment]
Java client has been released.
