### ISSUE TITLE
Document how to do batch writes

### ISSUE THREAD

**Issue by jacek99** [aerospike/aerospike-client-java#5]
I looked at the Batch example:

https://github.com/aerospike/aerospike-client-java/blob/master/examples/src/com/aerospike/examples/Batch.java

and it seems to do individual writes.

It is not clear from the docs or the examples how to do large batch saves (e.g. update 5000 different records in a single call, instead of 5000 separate saves).

It is possible to update different sets in the same batch? 

E.g. save 5000 records in one set, plus an audit trail record for each of them in a separate set, as part of the same operation?

**Comment by giena** [comment]
Sorry but when i do some benchmarks, inserting a lot of records (a key and a bin of 1 kbytes), i see all my indicators (CPU, IO network and disk) at a very low level. But the result is not so good (20000 records/sec ==> 25 Mbytes/sec). I think it's due to network and client/server latency. So with methods for a batch write (and batch delete) , i'm sure i could go more faster!

**Comment by bbulkow** [comment]
Louis,

How many threads is reasonable for your app?

Batches lower cpu consumption, io , network, disk, generally.

it also gets you ... essentially ... more parallelism, at least at the
database layer. this can be driven, somilarly, by greater threading. the
java client uses concurrent data structures and similar.

sent from my phone, please excuse any terseness

**Comment by jmizgajski** [comment]
Just to add some weight to why batches are important:

- there is no async python client 
- if you use celery you cannot use multiprocessing (which is untill now the most efficient way I found for writing batches in python)
- if you use multithreading you still cannot pass the 1k TPS in python
- so you face a choice - rip out celery in favour of much less mature python-rq which can do multiprocessing or chose a different db (couchbase happily accepts 3k TPS from a single python process with pipeline()) or chose a different language (hardly a choice if you are invested with other parts of the code)

I'm leaning closer and closer to choosing a different db:(

**Comment by Hammad2861** [comment]
I was wondering if there is an example on how to write data from a rdd into aerospike and how to read data from aerospike and create an rdd from it. If there is a link to that example would be nice. Thanks

**Comment by wchu-citrusleaf** [comment]
@Hammad2861 checkout the Launchpad at http://www.aerospike.com/launchpad/ which has a few Spark related examples.

**Comment by vikram1992** [comment]
Even I am fed up with aerospike...Cant delete the set and cant even do the batch processing
