### ISSUE TITLE
Cannot call lua method load

### ISSUE THREAD

**Issue by Osguima3** [aerospike/aerospike-client-java#50]
This lua method is not available in this client, while other clients, like the node.js one, do. We use this method to dynamically generate aggregation functions.

I was able to use this method by previously registering it manually so that Aerospike gets an instance with the method loaded. (This is a hacky way, probably there is a better one):

``` java
final LuaInstance instance = LuaCache.getInstance();
instance.registerPackage("load", LuaTable.tableOf(new LuaValue[] {
    LuaValue.valueOf("loadLib"), JsePlatform.standardGlobals().get("load") }));
LuaCache.putInstance(instance);
```

and then in lua

``` lua
local load = load or loadLib.load
local foo = load("return 'hi'");
info(foo()); -- Prints 'hi'
```

But this doesn't solve the problem if Aerospike decides it needs more instances than what the pool currently has.

**Comment by Osguima3** [comment]
I researched a bit more, and all that would be needed is:
``` java
import org.luaj.vm2.LoadState;

public LuaInstance() throws AerospikeException {
   ...
   LoadState.install(globals);
}
```

**Comment by BrianNichols** [comment]
We will add "LoadState.install(globals);" at the end of the LuaInstance constructor in the next java client release.

**Comment by BrianNichols** [comment]
Java client has been released.
