### ISSUE TITLE
Documentation pages aren't working

### ISSUE THREAD

**Issue by alexandrnikitin** [aerospike/aerospike-client-java#53]
I cannot open most pages of java client documentation. I.e.
http://www.aerospike.com/docs/client/java/usage/scan/scan.html
http://www.aerospike.com/docs/client/java/usage/kvs
http://www.aerospike.com/docs/client/java/usage/udf
etc

**Comment by BrianNichols** [comment]
Those pages are indeed broken.  We are working on a fix.

**Comment by ariane6** [comment]
Here is the full list of the pages/links that are broken. Clicking on the following links on this page: http://www.aerospike.com/docs/client/java/usage results in "Page Not Found" errors:

- any of the items underneath the word "Connecting" ("Key-Value Store", "User Defined Functions", "Query", "Aggregation", "Scan")
- the term "Large Data Types"
- the term "Asynchronous API" under "Error Handling"

Cross-linking this with a related issue on the Aerospike forum: https://discuss.aerospike.com/t/java-client-documentation/2056

**Comment by wchu-citrusleaf** [comment]
@alexandrnikitin the website has be fix. Thanks for bringing it to our attention!

**Comment by alexandrnikitin** [comment]
It works now. Thanks.
