### ISSUE TITLE
Potential Socket Leak 

### ISSUE THREAD

**Issue by ashwinjagadeesh** [aerospike/aerospike-client-java#60]
No socket.close when there is an exception in https://github.com/aerospike/aerospike-client-java/blob/master/client/src/com/aerospike/client/cluster/Connection.java#L57

**Comment by ashwinjagadeesh** [comment]
Also in the line https://github.com/aerospike/aerospike-client-java/blob/master/client/src/com/aerospike/client/cluster/Connection.java#L67 better to morph it to AerospikeException.Connection which can be easily handled by the caller function.

**Comment by BrianNichols** [comment]
Java client 3.2.5 was released today which fixes this problem.
