### ISSUE TITLE
Access control client implementation not in sync with Aerospike server

### ISSUE THREAD

**Issue by ashwinjagadeesh** [aerospike/aerospike-client-java#69]
According to the [documentation](http://www.aerospike.com/docs/guide/security/access-control.html
), access control can be applied at the namespace level. On the other hand there is no way AerospikeClient(one instance per cluster), can be created to have different ACL, across namespaces.

**Comment by BrianNichols** [comment]
You can create multiple AerospikeClient instances per cluster if using multiple security credentials.  This will incur some extra overhead (more connections, duplicate cluster tend threads), but it is definitely possible.
