### ISSUE TITLE
Multiple Async Client share with Same SelectorManagers

### ISSUE THREAD

**Issue by shanling2004** [aerospike/aerospike-client-java#71]
We have requirement to access multiple aerospike cluster with Async Client.
While we want to reuse one selector thread to handle multiple cluster's access, it requires Multiple Async Client share with Same SelectorManagers

**Comment by BrianNichols** [comment]
Each AsyncClient instance currently contains it's own set of selector threads.  The selector threads can't currently be shared.  We may revisit this design limitation in a future release.

**Comment by shanling2004** [comment]
Thanks @BrianNichols . The reason we propose this enhancement is because we will have multiple aerospike cluster underneath, we plan to enable async client with less IO selector thread to dispatch non-blocking requests in order to avoid unnecessary context switch or threading overhead.

However, currently IO selector thread number = policy.asyncSelectorThreads * <# of aerospike clusters>
[Selectormanager](https://github.com/aerospike/aerospike-client-java/blob/master/client/src/com/aerospike/client/async/SelectorManagers.java#L37)

**Comment by shanling2004** [comment]
Not sure we have timeline for shared selector thread support cross multiple clusters?

**Comment by BrianNichols** [comment]
There is no timeline right now.  We are looking into improving async java client performance and this change would be part of that task.

**Comment by shanling2004** [comment]
Thanks @BrianNichols . Looking forward for async client roadmap. Let's keep in touch :)

**Comment by BrianNichols** [comment]
Java client 4.0.0 has been released:

http://www.aerospike.com/download/client/java/4.0.0/

This version allows you to specify Netty or direct NIO event loops independently and share them with multiple AerospikeClient instances.  The new async methods in AerospikeClient add the target event loop as an argument.  These methods are intended as a replacement for the old AsyncClient.

**Comment by shanling2004** [comment]
Awesome @BrianNichols , we plan to integrate with async client 4.0.0 and give you the feeback.
