### ISSUE TITLE
Async client hangs with netty EpollEventLoopGroup

### ISSUE THREAD

**Issue by koeninger** [aerospike/aerospike-client-java#78]
Minimal change necessary to the /example subproject in order to reproduce the error:

https://github.com/koeninger/aerospike-client-java/commit/0723ae0644f33dd601ef78be580f599aa31b4281

**Comment by BrianNichols** [comment]
We will add support for epoll event loops in the next java client release.

**Comment by BrianNichols** [comment]
Java client 4.0.1 adds support for epoll event loops.

http://www.aerospike.com/download/client/java/4.0.1/
