### ISSUE TITLE
Access to last updated time for the key

### ISSUE THREAD

**Issue by ashwinjagadeesh** [aerospike/aerospike-client-java#82]
Since release of 3.8.3, we have last updated time available in the key.

Can we have it available in the [Record](https://github.com/aerospike/aerospike-client-java/blob/master/client/src/com/aerospike/client/Record.java)?

**Comment by BrianNichols** [comment]
The client will make last update time available when the server provides it in the wire protocol.  The server team is formulating a plan for this enhancement, but no timeline has been set.
