### ISSUE TITLE
waitTillComplete() not respone when run with command "java -cp..."

### ISSUE THREAD

**Issue by thanhlv93** [aerospike/aerospike-client-java#85]
Hello,
I tried to update records ttl and run with command : 

`           
            java -cp libs/*:. Myclass`

My code  : 
`

            Statement stmt1 = new Statement();
            stmt1.setNamespace(Const.AS_NAMESPACE);
            stmt1.setSetName(Const.AS_SET_QOS_REAL_TIME_SUMMARY);
            ExecuteTask task = mAsClient.execute(null, stmt1, "aggregate", "set_ttl", new Value.IntegerValue(1));
            System.out.println("Waiting....");
            task.waitTillComplete();
            System.out.println("task.queryStatus() = " + task.queryStatus());
`

My log stoped at line : task.waitTillComplete(); 
and this line is never call:
 
System.out.println("task.queryStatus() = " + task.queryStatus()); 

I'm using new version 4.0.7 .

Please tell me if you have any suggest .
Thank all.

**Comment by BrianNichols** [comment]
Did either execute() or wailtTIllComplete() throw an exception?

**Comment by thanhlv93** [comment]
@BrianNichols  Does not throw exception . After change this live : 

      System.out.println("task.queryStatus() = " + task.queryStatus());

to

      System.out.println("Update success !");

It's working perfect .
