### ISSUE TITLE
createIndex should return whether index already exists 

### ISSUE THREAD

**Issue by Aloren** [aerospike/aerospike-client-java#88]
Currently `createIndex` operation in `AerospikeClient` returns `IndexTask` for both cases: index does not exist, index already exists. In case we want to know whether it existed previously there are no means of doing it with current API.

**Comment by BrianNichols** [comment]
For versions >= 4.1.0: If the index already exists, createIndex() will throw an exception.  The exception resultCode will be `ResultCode.INDEX_ALREADY_EXISTS`.

**Comment by Aloren** [comment]
Great news! Thank you!
