### ISSUE TITLE
dropIndex should provide api to wait until operation is completed

### ISSUE THREAD

**Issue by Aloren** [aerospike/aerospike-client-java#89]
Currently `AerospikeClient` provides API for creation and deletion of index. When creating index it is possible to wait until it is created using `IndexTask.waitTillComplete`, but the same API is missing for deletion.

**Comment by BrianNichols** [comment]
We will look into returning a DropIndexTask from dropIndex() in a future client release.

**Comment by BrianNichols** [comment]
IndexTask is now returned from dropIndex() in Java client 4.1.3.

https://www.aerospike.com/download/client/java/4.1.3/
