### ISSUE TITLE
Key not Serializable problem when mocking IAerospikeClient.java

### ISSUE THREAD

**Issue by fpopic** [aerospike/aerospike-client-java#90]
Hi, 

Is there a possibility to mock somehow [IAerospikeClient](https://github.com/aerospike/aerospike-client-java/blob/master/client/src/com/aerospike/client/IAerospikeClient.java) interface in Scala/Java using any mocking library like `mock<IAerospikeClient>` avoiding  

`Caused by: java.io.NotSerializableException: com.aerospike.client.Key not Serializable`

when sending the client over the network (for example, sending the client to Google Dataflow workers)

Would pull request with: 

`public interface IAerospikeClient extends Closeable, Serializable` 

solve the problem (of course all object that client uses need to be also Serializable)?

**Comment by BrianNichols** [comment]
I recommend trying to fix the java client to handle your use-case.  If it works, issue a pull request.
