### ISSUE TITLE
Behavior of createIndex changed

### ISSUE THREAD

**Issue by Aloren** [aerospike/aerospike-client-java#94]
After introducing TaskIndex for `dropIndex` method in this [commit](https://github.com/aerospike/aerospike-client-java/commit/08680d82fa0593c927dd82452b24a832a0d086f1) the behavior of `createIndex` changed for case when index already exists.
Previously `createIndex` if index already existed did not fail with exception. In version 4.1.3 it fails with the following message:
```
Create index failed: FAIL:200:Index with the same name already exists or this bin has already been indexed.
```
Is that an expected behavior or regression?

Thanks.

**Comment by BrianNichols** [comment]
This is the new expected behavior.  See release notes:

https://www.aerospike.com/download/client/java/notes.html#4.1.0

**Comment by Aloren** [comment]
Great. Thank you!

**Comment by monrealis** [comment]
So what's the idemponent way to create index now?

**Comment by BrianNichols** [comment]
See https://www.aerospike.com/docs/client/java/usage/incompatible.html and find section "Version 4.1.0 - LDT Removal and Index Exceptions".

**Comment by monrealis** [comment]
Sure, I see that and I have already done that.

**Comment by BrianNichols** [comment]
I don't understand your question.
